POST http://localhost:8082
Content-Type: application/json

{
    "jsonrpc": "2.0",
    "id": 12345,
    "method": "geo.suburb_number.age",
    "params": {"suburb_number": "102", "sort_by": "number"}
}